development:
  secret_key_base: # run 'bundle exec rake secret' and paste the result here.  remember to change the name of this file to 'secrets.yml'
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>