# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d0ebfc1c7fcde4e7f9dda8f2b2ee5edffca20e28094906531fb38584832d0413fe2deb51ca0aec3b4378f83d9f171debe08ff13ec3eb192263f7c595e8988d

test:
  secret_key_base: d143c51d0e0c96c36f465b5c7874e5f080058ea060bfd75a7da7b3be4f1a4f8d338cdb49d29d2a8ca0be3a628df641394ddcea1f8acbb0a02577c54854d45511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
